version: "3.8"

services:
    web:
        build: .
        ports:
            - "443:443"
        volumes:
            - .:/code
        environment:
            - DATABASE_URL=postgresql+psycopg2://postgres:H2XyzCTjdNbf9NVWGwYx@containers-us-west-175.railway.app:7892/railway
        
