"""users1

Revision ID: 30164f1d850e
Revises: d16fb9534327
Create Date: 2023-09-07 18:09:39.076474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30164f1d850e'
down_revision: Union[str, None] = 'd16fb9534327'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=True),
    sa.Column('token_type', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tokens_id'), 'tokens', ['id'], unique=False)
    op.drop_index('ix_people_cel_number', table_name='people')
    op.drop_index('ix_people_city', table_name='people')
    op.drop_index('ix_people_dress', table_name='people')
    op.drop_index('ix_people_first_name', table_name='people')
    op.drop_index('ix_people_last_name', table_name='people')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_people_last_name', 'people', ['last_name'], unique=False)
    op.create_index('ix_people_first_name', 'people', ['first_name'], unique=False)
    op.create_index('ix_people_dress', 'people', ['dress'], unique=False)
    op.create_index('ix_people_city', 'people', ['city'], unique=False)
    op.create_index('ix_people_cel_number', 'people', ['cel_number'], unique=False)
    op.drop_index(op.f('ix_tokens_id'), table_name='tokens')
    op.drop_table('tokens')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
